import { NextRequest, NextResponse } from 'next/server';
import { withTransaction, query } from '@/lib/db';
import { createErrorResponse, withErrorHandling } from '@/lib/errors';
import { logger } from '@/lib/logger';
import { z } from 'zod';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

// Error report schema
const ErrorReportSchema = z.object({
  type: z.enum(['bad_block', 'crash', 'sync_stall', 'peer_crisis']),
  blockNumber: z.number().optional().nullable(),
  errorMessage: z.string().max(1000).optional(),
  details: z.record(z.any()).optional().nullable(),
});

// Map client types to GitHub repos
const CLIENT_REPO_MAP: Record<string, string> = {
  'geth': 'go-ethereum',
  'gp5': 'go-ethereum',
  'erigon': 'erigon-xdc',
  'nethermind': 'nethermind',
  'XDC': 'go-ethereum',
  'unknown': 'go-ethereum',
};

// Map error types to human-readable titles
const ERROR_TYPE_TITLES: Record<string, string> = {
  'bad_block': 'Bad Block Detected',
  'crash': 'Node Crash/Panic',
  'sync_stall': 'Sync Stalled',
  'peer_crisis': 'Peer Connection Crisis',
};

/**
 * Check if an error of this type has already been reported for this node
 */
async function hasExistingError(
  nodeId: string,
  errorType: string,
  sinceMinutes: number = 60
): Promise<{ exists: boolean; githubIssueUrl?: string }> {
  const result = await query(
    `SELECT github_issue_url 
     FROM skynet.node_errors 
     WHERE node_id = $1 
       AND error_type = $2 
       AND created_at > NOW() - INTERVAL '${sinceMinutes} minutes'
     ORDER BY created_at DESC 
     LIMIT 1`,
    [nodeId, errorType]
  );
  
  if (result.rows.length > 0) {
    return { 
      exists: true, 
      githubIssueUrl: result.rows[0].github_issue_url 
    };
  }
  return { exists: false };
}

/**
 * Create a GitHub issue for the error
 */
async function createGitHubIssue(
  clientType: string,
  nodeName: string,
  nodeId: string,
  errorType: string,
  blockNumber: number | null | undefined,
  errorMessage: string | undefined,
  details: any
): Promise<string | null> {
  const repo = CLIENT_REPO_MAP[clientType.toLowerCase()] || 'go-ethereum';
  const title = `[${nodeName}] ${ERROR_TYPE_TITLES[errorType] || errorType}`;
  
  const body = `## Error Report

**Node:** ${nodeName}
**Node ID:** ${nodeId}
**Error Type:** ${errorType}
**Client:** ${clientType}
**Reported At:** ${new Date().toISOString()}

### Details

${blockNumber ? `**Block Number:** ${blockNumber}` : ''}
${errorMessage ? `**Error Message:**\n\`\`\`\n${errorMessage}\n\`\`\`` : ''}

${details ? `**Additional Details:**\n\`\`\`json\n${JSON.stringify(details, null, 2)}\n\`\`\`` : ''}

---
*This issue was auto-generated by SkyNet monitoring.*
`;

  try {
    // Check if gh CLI is available
    const { stdout: ghCheck } = await execAsync('which gh');
    if (!ghCheck.trim()) {
      logger.warn('GitHub CLI (gh) not found, skipping issue creation');
      return null;
    }

    // Create the issue using gh CLI
    const { stdout, stderr } = await execAsync(
      `gh issue create --repo AnilChinchawale/${repo} --title "${title.replace(/"/g, '\\"')}" --body "${body.replace(/"/g, '\\"').replace(/\$/g, '\\$')}" --label "bug,skynet"`,
      { timeout: 30000 }
    );

    if (stdout) {
      // Extract issue URL from output
      const issueUrl = stdout.trim();
      logger.info('GitHub issue created', { 
        repo: `AnilChinchawale/${repo}`,
        issueUrl,
        nodeId,
        errorType 
      });
      return issueUrl;
    }
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : String(err);
    logger.error(`Failed to create GitHub issue for repo AnilChinchawale/${repo}: ${errorMessage}`);
  }
  
  return null;
}

/**
 * POST /api/v1/nodes/{id}/errors
 * Report an error from a node
 */
async function postHandler(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const nodeId = params.id;
  
  // Verify node exists and get its details
  const nodeResult = await query(
    'SELECT id, name, client_type FROM skynet.nodes WHERE id = $1',
    [nodeId]
  );
  
  if (nodeResult.rows.length === 0) {
    return NextResponse.json(
      { success: false, error: 'Node not found' },
      { status: 404 }
    );
  }
  
  const node = nodeResult.rows[0];
  
  const body = await request.json();
  
  // Validate request body
  const validation = ErrorReportSchema.safeParse(body);
  if (!validation.success) {
    return NextResponse.json(
      { 
        success: false, 
        error: 'Validation failed',
        details: validation.error.errors 
      },
      { status: 400 }
    );
  }

  const data = validation.data;
  
  try {
    // Check if this error type was already reported recently for this node
    const existingError = await hasExistingError(nodeId, data.type);
    
    let githubIssueUrl: string | null = null;
    
    // Only create GitHub issue if this is a new error type for this node
    if (!existingError.exists) {
      githubIssueUrl = await createGitHubIssue(
        node.client_type || 'unknown',
        node.name,
        nodeId,
        data.type,
        data.blockNumber,
        data.errorMessage,
        data.details
      );
    } else {
      githubIssueUrl = existingError.githubIssueUrl || null;
    }
    
    // Store the error in the database
    const result = await withTransaction(async (client) => {
      const insertResult = await client.query(
        `INSERT INTO skynet.node_errors 
         (node_id, error_type, block_number, error_message, details, github_issue_url)
         VALUES ($1, $2, $3, $4, $5, $6)
         RETURNING id, created_at`,
        [
          nodeId,
          data.type,
          data.blockNumber || null,
          data.errorMessage || null,
          data.details ? JSON.stringify(data.details) : null,
          githubIssueUrl,
        ]
      );
      
      return insertResult.rows[0];
    });

    logger.info('Node error reported', { 
      nodeId, 
      errorType: data.type,
      errorId: result.id,
      githubIssueUrl,
      isNewIssue: !existingError.exists
    });

    return NextResponse.json({
      success: true,
      data: {
        errorId: result.id,
        githubIssueUrl,
        isNewIssue: !existingError.exists,
        createdAt: result.created_at,
      },
      message: existingError.exists 
        ? 'Error logged (GitHub issue already exists)'
        : 'Error logged and GitHub issue created',
    }, { status: 201 });

  } catch (error: any) {
    console.error('Error reporting error:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: error.message || 'Error reporting failed' 
      },
      { status: 500 }
    );
  }
}

/**
 * GET /api/v1/nodes/{id}/errors
 * Get error history for a node
 */
export async function GET(
  request: NextRequest,
  { params }: { params: { id: string } }
) {
  const nodeId = params.id;
  
  try {
    // Verify node exists
    const nodeResult = await query(
      'SELECT id FROM skynet.nodes WHERE id = $1',
      [nodeId]
    );
    
    if (nodeResult.rows.length === 0) {
      return NextResponse.json(
        { success: false, error: 'Node not found' },
        { status: 404 }
      );
    }
    
    // Get error history
    const errorsResult = await query(
      `SELECT 
        id, error_type, block_number, error_message, 
        details, github_issue_url, created_at
       FROM skynet.node_errors 
       WHERE node_id = $1 
       ORDER BY created_at DESC 
       LIMIT 100`,
      [nodeId]
    );
    
    return NextResponse.json({
      success: true,
      data: {
        nodeId,
        errors: errorsResult.rows.map(row => ({
          ...row,
          details: row.details ? JSON.parse(row.details) : null,
        })),
      },
    });
  } catch (error: any) {
    console.error('Error fetching error history:', error);
    return NextResponse.json(
      { 
        success: false, 
        error: error.message || 'Failed to fetch error history' 
      },
      { status: 500 }
    );
  }
}

export const POST = withErrorHandling(postHandler);
