import { NextRequest, NextResponse } from 'next/server';
import { Pool } from 'pg';
import { execSync } from 'child_process';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL || 'postgresql://gateway:***@localhost:5433/xdc_gateway',
});

interface GitHubEscalationPayload {
  incidentId: number;
  clientType?: string;
  network?: string;
}

// Determine GitHub repo based on client type
function getRepoForClient(clientType: string): string {
  const normalized = clientType.toLowerCase();
  
  if (normalized.includes('geth') || normalized.includes('pr5')) {
    return 'AnilChinchawale/go-ethereum';
  } else if (normalized.includes('nethermind')) {
    return 'AnilChinchawale/nethermind';
  } else if (normalized.includes('erigon')) {
    return 'AnilChinchawale/erigon-xdc';
  }
  
  // Default to go-ethereum
  return 'AnilChinchawale/go-ethereum';
}

// Format incident details for GitHub issue
function formatIncidentForGitHub(incident: any, node: any, playbook: any): { title: string; body: string; labels: string[] } {
  const title = `[${incident.severity.toUpperCase()}] ${incident.type.replace(/_/g, ' ')}: ${incident.message.substring(0, 80)}`;
  
  const context = incident.context || {};
  const lastLogs = context.last_logs || [];
  const errorPatterns = context.error_patterns || [];
  
  let body = `## Incident Report\n\n`;
  body += `**Type:** ${incident.type}\n`;
  body += `**Severity:** ${incident.severity}\n`;
  body += `**Node:** ${node.name} (${node.client_type} ${context.version || 'unknown'})\n`;
  body += `**Network:** ${node.network}\n`;
  body += `**Occurrences:** ${incident.occurrence_count}\n`;
  body += `**First Seen:** ${incident.first_seen}\n`;
  body += `**Last Seen:** ${incident.last_seen}\n`;
  body += `**Fingerprint:** \`${incident.fingerprint}\`\n\n`;

  body += `## Description\n\n${incident.message}\n\n`;

  if (context.block) {
    body += `## Chain State\n\n`;
    body += `- **Block:** ${context.block}\n`;
    body += `- **Peers:** ${context.peers || 'unknown'}\n`;
    if (context.duration_min) {
      body += `- **Duration:** ${context.duration_min} minutes\n`;
    }
    body += `\n`;
  }

  if (errorPatterns.length > 0) {
    body += `## Error Patterns\n\n`;
    errorPatterns.forEach((pattern: string) => {
      body += `- \`${pattern}\`\n`;
    });
    body += `\n`;
  }

  if (lastLogs.length > 0) {
    body += `## Recent Logs\n\n\`\`\`\n`;
    lastLogs.slice(-20).forEach((log: string) => {
      body += `${log}\n`;
    });
    body += `\`\`\`\n\n`;
  }

  body += `## Auto-Heal Attempts\n\n`;
  body += `- **Action:** ${incident.heal_action || 'none'}\n`;
  body += `- **Success:** ${incident.heal_success ? '✅ Yes' : '❌ No'}\n`;
  body += `- **Attempts:** ${incident.heal_attempts}\n\n`;

  // Find playbook entry for suggested fix
  const playbookEntry = playbook?.playbook?.find((entry: any) => entry.id === incident.type);
  if (playbookEntry?.suggested_fix) {
    body += `## Suggested Fix\n\n${playbookEntry.suggested_fix}\n\n`;
  }

  body += `## System Info\n\n`;
  body += `- **CPU:** ${context.cpu_percent || 'unknown'}%\n`;
  body += `- **Memory:** ${context.mem_percent || 'unknown'}%\n`;
  body += `- **Disk:** ${context.disk_percent || 'unknown'}%\n\n`;

  body += `---\n*Auto-generated by SkyNet AI Issue Intelligence*\n`;
  body += `*Incident ID: ${incident.id}*`;

  // Determine labels (only use labels that exist on the repo)
  const labels = [incident.severity];
  if (playbookEntry?.escalate?.labels) {
    labels.push(...playbookEntry.escalate.labels);
  }

  return { title, body, labels: [...new Set(labels)] };
}

// POST /api/v1/incidents/github — escalate incident to GitHub
export async function POST(request: NextRequest) {
  try {
    const payload: GitHubEscalationPayload = await request.json();

    if (!payload.incidentId) {
      return NextResponse.json(
        { success: false, error: 'Missing required field: incidentId' },
        { status: 400 }
      );
    }

    // Fetch incident details with node info
    const result = await pool.query(
      `SELECT i.*, n.name as node_name, n.client_type, n.network, n.client_version as version
       FROM skynet.incidents i
       LEFT JOIN skynet.nodes n ON i.node_id = n.id
       WHERE i.id = $1`,
      [payload.incidentId]
    );

    if (result.rows.length === 0) {
      return NextResponse.json(
        { success: false, error: 'Incident not found' },
        { status: 404 }
      );
    }

    const incident = result.rows[0];
    const node = {
      name: incident.node_name,
      client_type: incident.client_type || payload.clientType,
      network: incident.network || payload.network,
    };

    // Load playbook
    const fs = require('fs');
    let playbook;
    try {
      const playbookPath = '/root/.openclaw/workspace/XDC-Node-Setup/configs/healing-playbook.json';
      const playbookContent = fs.readFileSync(playbookPath, 'utf8');
      playbook = JSON.parse(playbookContent);
    } catch (e) {
      console.warn('Could not load playbook:', e);
    }

    // Determine repo
    const playbookEntry = playbook?.playbook?.find((entry: any) => entry.id === incident.type);
    let repo = playbookEntry?.escalate?.github_repo;
    
    if (!repo || repo === 'auto') {
      repo = getRepoForClient(node.client_type);
    }

    if (!repo) {
      return NextResponse.json(
        { success: false, error: 'Could not determine GitHub repository' },
        { status: 400 }
      );
    }

    // Format issue content
    const { title, body, labels } = formatIncidentForGitHub(incident, node, playbook);

    // Search for existing issue with fingerprint
    let existingIssueNumber: number | null = null;
    try {
      const searchQuery = incident.fingerprint;
      const searchCmd = `gh issue list --repo ${repo} --state open --search "${searchQuery}" --json number,title --limit 5`;
      const searchResult = execSync(searchCmd, { encoding: 'utf8', timeout: 10000 });
      const issues = JSON.parse(searchResult);
      
      // Check if any issue matches our fingerprint in the body
      for (const issue of issues) {
        try {
          const viewCmd = `gh issue view ${issue.number} --repo ${repo} --json body`;
          const viewResult = execSync(viewCmd, { encoding: 'utf8', timeout: 10000 });
          const issueData = JSON.parse(viewResult);
          
          if (issueData.body && issueData.body.includes(incident.fingerprint)) {
            existingIssueNumber = issue.number;
            break;
          }
        } catch (e) {
          console.warn(`Could not check issue ${issue.number}:`, e);
        }
      }
    } catch (error) {
      console.warn('Could not search existing issues:', error);
    }

    let issueUrl: string;
    let issueNumber: number;
    let action: string;

    if (existingIssueNumber) {
      // Update existing issue with comment
      const comment = `## New Occurrence Detected\n\n`;
      const commentBody = `**Timestamp:** ${new Date().toISOString()}\n` +
        `**Occurrence Count:** ${incident.occurrence_count}\n` +
        `**Block:** ${incident.context?.block || 'unknown'}\n` +
        `**Peers:** ${incident.context?.peers || 'unknown'}\n` +
        `**Heal Success:** ${incident.heal_success ? '✅' : '❌'}\n\n` +
        `Still experiencing this issue. Auto-heal attempts: ${incident.heal_attempts}`;

      const os = require('os');
      const path = require('path');
      const tmpCommentFile = path.join(os.tmpdir(), `skynet-comment-${Date.now()}.md`);
      fs.writeFileSync(tmpCommentFile, comment + commentBody);
      try {
        const commentCmd = `gh issue comment ${existingIssueNumber} --repo ${repo} --body-file ${tmpCommentFile}`;
        execSync(commentCmd, { encoding: 'utf8', timeout: 10000 });
      } finally {
        try { fs.unlinkSync(tmpCommentFile); } catch (e) {}
      }

      // Update labels if severity changed
      const labelsStr = labels.join(',');
      const labelCmd = `gh issue edit ${existingIssueNumber} --repo ${repo} --add-label "${labelsStr}"`;
      try {
        execSync(labelCmd, { encoding: 'utf8', timeout: 10000 });
      } catch (e) {
        console.warn('Could not update labels:', e);
      }

      issueNumber = existingIssueNumber;
      issueUrl = `https://github.com/${repo}/issues/${existingIssueNumber}`;
      action = 'commented';

      console.log(`Added comment to existing issue #${existingIssueNumber}`);
    } else {
      // Create new issue (use temp file to avoid shell escaping issues with backticks)
      const labelsStr = labels.join(',');
      const os = require('os');
      const path = require('path');
      const tmpFile = path.join(os.tmpdir(), `skynet-issue-${Date.now()}.md`);
      fs.writeFileSync(tmpFile, body);
      let createResult: string;
      try {
        const createCmd = `gh issue create --repo ${repo} --title ${JSON.stringify(title)} --body-file ${tmpFile} --label "${labelsStr}"`;
        createResult = execSync(createCmd, { encoding: 'utf8', timeout: 15000 });
      } finally {
        try { fs.unlinkSync(tmpFile); } catch (e) {}
      }
      issueUrl = createResult.trim();
      
      // Extract issue number from URL
      const match = issueUrl.match(/\/issues\/(\d+)/);
      issueNumber = match ? parseInt(match[1]) : 0;

      action = 'created';

      console.log(`Created new issue: ${issueUrl}`);
    }

    // Update incident with GitHub info
    await pool.query(
      `UPDATE skynet.incidents 
       SET github_issue_url = $1, github_issue_number = $2, status = 'escalated'
       WHERE id = $3`,
      [issueUrl, issueNumber, incident.id]
    );

    return NextResponse.json({
      success: true,
      action,
      issueUrl,
      issueNumber,
      repo,
    });
  } catch (error: any) {
    console.error('Error escalating to GitHub:', error);
    return NextResponse.json(
      { success: false, error: error.message, stack: error.stack },
      { status: 500 }
    );
  }
}
